
image: docker.gitlab.gwdg.de/app/cip-pool-image:latest
stages:
  - build
  - dist
  - deploy

variables:
  DEBIAN_FRONTEND: noninteractive

# build-code:
#   stage: build
#   script:
#     - make build
#   artifacts:
#     paths:
#       - "./build/libpreset.a"
#       - "./include"

build-doc:
  stage: build
  script:
    - doxygen
  artifacts:
    paths:
      - "./doc/html"

dist:
  stage: dist
  needs: ["build-doc"]
  script:
    - make dist
  artifacts:
    paths:
      - "./preset/"
      - "./preset-release.zip"
    expire_in: never
  #rules:
  #  - if: '$CI_COMMIT_TAG =~ /\Av\d+\.\d+\.\d+\z/'
  #only:
  #  - main


pages:
  stage: deploy
  needs: ["build-doc", "dist"]
  script:
    - mkdir -p "./public/"
    - ls -lahR "./public/"
    - cp -rv "./doc/html" "./public/doc"
    - cp -rv "./preset" "./public/preset"
    - cp -v "./preset-release.zip" "./public/"
    - ls -lahR "./public/"
    - echo "Publishing contents of public/"
  artifacts:
    expire_in: never
    paths:
      - "./public/"
  only:
    - main

